# Generated by Django 3.0.8 on 2020-07-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('secret', '0002_auto_20200712_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='owner_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_group', to='auth.Group'),
        ),
    ]
