# Generated by Django 3.0.8 on 2020-07-14 17:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0003_auto_20200712_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='secret',
            name='details',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
        migrations.AlterField(
            model_name='secret',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
    ]
