# Generated by Django 3.0.8 on 2020-07-19 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secret', '0004_auto_20200714_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='owner_group',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='viewer_groups',
        ),
        migrations.AlterField(
            model_name='secret',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
