# Generated by Django 3.0.8 on 2021-01-18 16:40

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("secret", "0006_secretgroupobjectpermission_secretuserobjectpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="mfa_string",
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.CreateModel(
            name="MFAClient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mfa_string", models.CharField(max_length=255)),
                (
                    "secret",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="secret.Secret"
                    ),
                ),
            ],
        ),
    ]
