# Generated by Django 3.1.13 on 2021-11-18 14:26

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0008_auto_20211112_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', django_cryptography.fields.encrypt(models.BinaryField(null=True))),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret.secret')),
            ],
        ),
    ]
