repos:
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
    - id: black
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
