version: '3'

volumes:
  passman-data:
    driver: local

services:
  db:
    image: "postgres:10"
    restart: always
    environment:
      - POSTGRESS_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=secrets
    volumes:
     - passman-data:/var/lib/postgresql/data
    ports:
     - 5432:5432
  web:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PORT=8000
      - DATABASE_URL=postgres://postgres:password@db:5432/secrets
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
