version: 2
jobs:
  build:
    docker:
      - image: python:3.8.2

      - image: postgres:9.6
        environment:
          POSTGRES_DB: secrets
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust

    environment:
      DATABASE_URL: postgresql://postgres@localhost/secrets

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          name: Restore pip cache
          keys:
            - v1-passman-{{ checksum "requirements-dev.txt" }}
            - v1-passman-
          paths:
            - ~/cache/pip

      - run:
          name: Install dependencies
          command: python -m pip install --cache-dir ~/cache/pip -r requirements-dev.txt

      - save_cache:
          name: Save pip cache
          key: v1-passman-{{ checksum "requirements-dev.txt" }}
          paths:
            - ~/cache/pip

      - run:
          name: Run tests
          command: python -m pytest --cov -s --junitxml=test-reports/junit.xml 

      - store_test_results:
          path: test-reports
