version: 2.1
jobs:
  build:
    docker:
      # If we upgrade python for this code base we can probably lose
      # the pip upgrade in the install dependencies step below
      - image: python:3.10.14
      - image: postgres:15.5
        environment:
          POSTGRES_DB: secrets
          POSTGRES_HOST_AUTH_METHOD: trust

    environment:
      DATABASE_URL: postgres://postgres@localhost:5432/secrets

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
          paths:
            - ~/cache/pip

      # Add ZBAR
      - run: apt-get update && apt-get -y install libzbar-dev

      - run:
          name: install dependencies
          command: |
            python -m pip install --cache-dir ~/cache/pip -r requirements.txt

      - save_cache:
          paths:
            - ~/cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            python -m pytest --cov-report xml --cov=.
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
