version: 2.1
jobs:
  build:
    docker:
      # If we upgrade python for this code base we can probably lose
      # the pip upgrade in the install dependencies step below
      - image: circleci/python:3.8.3
      - image: postgres:12.3
        environment:
          POSTGRES_DB: secrets
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Add ZBAR
      - run: sudo apt-get --allow-releaseinfo-change update && sudo apt-get install libzbar-dev

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip --version
            python3 -m pip install --upgrade pip
            pip --version
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            env
            py.test --cov-report xml --cov=.
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
