# Generated by Django 3.0.8 on 2020-07-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("secret", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="secret",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="secret.Secret"
            ),
        ),
    ]
