# Generated by Django 3.1.13 on 2021-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20200812_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(choices=[('imported', 'Imported'), ('create_secret', 'Created'), ('update_secret', 'Updated'), ('delete_secret', 'Deleted'), ('view_secret', 'Viewed'), ('add_permission', 'Added permission'), ('remove_permission', 'Removed permission'), ('setup_mfa', 'Set up MFA client'), ('delete_mfa', 'Delete MFA client'), ('generate_mfa_token', 'Generate MFA token')], max_length=255),
        ),
    ]
